version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./symfony/:/var/www/html/
    web:
        image: nginx:latest
        ports:
          - "8070:80"
        volumes:
          - ./nginx/conf.d/:/etc/nginx/conf.d/
          - ./symfony/:/var/www/html/
